### ISSUE TITLE
Build failed with NPE

### ISSUE THREAD

**Issue by rbtr** [denley/PreferenceInjector#32]
I'm getting a build failure with this library. Relevant section of stacktrace:

Caused by: java.lang.NullPointerException
        at me.denley.preferencebinder.internal.BindingCallCodeAnalyzer.visitMethod(BindingCallCodeAnalyzer.java:31)
        at me.denley.preferencebinder.internal.BindingCallCodeAnalyzer.visitMethod(BindingCallCodeAnalyzer.java:13)
        at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:800)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:68)
        at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:81)
        at com.sun.source.util.TreeScanner.scan(TreeScanner.java:91)
        at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:99)
        at com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:133)
        at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:720)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:50)
        at me.denley.preferencebinder.internal.PreferenceBinderProcessor.classMakesStatementCall(PreferenceBinderProcessor.java:334)
        at me.denley.preferencebinder.internal.PreferenceBinderProcessor.checkForBindingCalls(PreferenceBinderProcessor.java:310)
        at me.denley.preferencebinder.internal.PreferenceBinderProcessor.findAndParseAnnotations(PreferenceBinderProcessor.java:100)
        at me.denley.preferencebinder.internal.PreferenceBinderProcessor.process(PreferenceBinderProcessor.java:76)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
        at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
        at com.sun.tools.javac.main.Main.compile(Main.java:523)
        ... 66 more

**Comment by denley** [comment]
Thanks for posting the stack trace. I'm looking into it now.

Would you mind sharing the class you are using this library in? It will help me understand the cause.

**Comment by denley** [comment]
Actually, I've managed to reproduce it. It happens when you use the library in an abstract class with an abstract method.

**Comment by denley** [comment]
I've just released version 3.0.1, which includes a fix for this issue.

Please reopen this issue if you find that it's still not fully fixed yet.

**Comment by rbtr** [comment]
Confirming the issue is fixed, builds with no errors.
Thanks for the quick response and nice work!
